import type { Category, Job, Source } from './types.js';
import { relativeTime } from './utils.js';

export interface RenderStats {
  generatedAt: string;
  fetchedTotal: number;
  keptTotal: number;
  bySource: Record<Source, { fetched: number; kept: number }>;
  byCategory: Record<Category, number>;
  droppedHard: number;
  droppedScore: number;
  removedById: number;
  removedByTitle: number;
}

const SOURCES: Source[] = [
  'ashby',
  'lever',
  'greenhouse',
  'cryptojobslist',
  'web3career',
  'aijobsnet',
  'hn-hiring',
  'hn-jobs',
  'remotive',
  'weworkremotely',
  'remoteok',
];

const CATEGORIES: Category[] = ['web3+ai', 'web3', 'ai', 'general'];

function escapeMd(s: string | null | undefined): string {
  if (!s) return '';
  return s.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').slice(0, 120);
}

function row(job: Job): string {
  const title = escapeMd(job.title);
  const company = escapeMd(job.company ?? '—');
  const posted = job.postedAt ? relativeTime(job.postedAt) : '—';
  const link = `[apply](${job.url})`;
  return `| ${job.fitScore} | ${title} | ${company} | ${job.source} | ${posted} | ${link} |`;
}

function renderTable(jobs: Job[], limit: number): string {
  if (jobs.length === 0) return '_No jobs in this category right now._\n';
  const header = '| Score | Title | Company | Source | Posted | Link |';
  const sep = '|------:|-------|---------|--------|--------|------|';
  const body = jobs.slice(0, limit).map(row).join('\n');
  return `${header}\n${sep}\n${body}\n`;
}

function bySource(stats: RenderStats): string {
  const lines: string[] = [];
  for (const s of SOURCES) {
    const v = stats.bySource[s];
    if (!v) continue;
    lines.push(`- **${s}**: ${v.fetched} fetched → ${v.kept} kept`);
  }
  return lines.join('\n');
}

function byCategory(stats: RenderStats): string {
  return CATEGORIES.map((c) => `- **${c}**: ${stats.byCategory[c]}`).join('\n');
}

export function renderReadme(jobs: Job[], stats: RenderStats): string {
  const grouped: Record<Category, Job[]> = {
    'web3+ai': [],
    web3: [],
    ai: [],
    general: [],
  };
  for (const j of jobs) grouped[j.category].push(j);

  return `# Daily job matches

Auto-generated by the [job-hunt](./README.md) pipeline. Do not edit by hand — this file is overwritten on every run.

**Last updated:** ${stats.generatedAt}

## Stats

- **Total fetched (raw):** ${stats.fetchedTotal}
- **Total kept (after filters + dedup):** ${stats.keptTotal}
- **Dropped — hard filters:** ${stats.droppedHard}
- **Dropped — fit score below 30:** ${stats.droppedScore}
- **Removed duplicates by URL:** ${stats.removedById}
- **Removed duplicates by company+title:** ${stats.removedByTitle}

### By source

${bySource(stats)}

### By category

${byCategory(stats)}

## Top Web3 + AI

${renderTable(grouped['web3+ai'], 10)}

## Top Web3

${renderTable(grouped.web3, 20)}

## Top AI

${renderTable(grouped.ai, 20)}

## Other

${renderTable(grouped.general, 10)}
`;
}
