name: keepalive

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  touch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Touch keepalive file
        run: date -u +%FT%TZ > .keepalive

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5
        with:
          commit_message: 'chore: keepalive'
          file_pattern: '.keepalive'
